export type CharadesDifficulty = "easy" | "medium" | "hard";

export type CharadesPrompt = {
  word: string;
  aliases: string[];
};

const EASY_WORDS = [
  "apple",
  "banana",
  "orange",
  "grape",
  "pear",
  "peach",
  "strawberry",
  "watermelon",
  "pizza",
  "burger",
  "fries",
  "cake",
  "cookie",
  "donut",
  "icecream",
  "bread",
  "egg",
  "milk",
  "coffee",
  "carrot",
  "sun",
  "moon",
  "star",
  "cloud",
  "rainbow",
  "rain",
  "snow",
  "tree",
  "flower",
  "leaf",
  "grass",
  "mountain",
  "river",
  "lake",
  "ocean",
  "beach",
  "fire",
  "house",
  "castle",
  "bridge",
  "road",
  "car",
  "bus",
  "train",
  "bike",
  "boat",
  "plane",
  "rocket",
  "submarine",
  "helicopter",
  "truck",
  "tractor",
  "motorcycle",
  "scooter",
  "balloon",
  "kite",
  "book",
  "pencil",
  "eraser",
  "scissors",
  "ruler",
  "backpack",
  "phone",
  "laptop",
  "camera",
  "clock",
  "key",
  "lock",
  "door",
  "window",
  "chair",
  "table",
  "bed",
  "sofa",
  "lamp",
  "toothbrush",
  "toothpaste",
  "soap",
  "umbrella",
  "hat",
  "shoe",
  "sock",
  "shirt",
  "pants",
  "dress",
  "glasses",
  "watch",
  "ring",
  "dog",
  "cat",
  "fish",
  "bird",
  "horse",
  "cow",
  "pig",
  "sheep",
  "rabbit",
  "turtle",
  "frog",
  "snail",
] as const;

const MEDIUM_WORDS = [
  "guitar",
  "violin",
  "piano",
  "drum",
  "trumpet",
  "microphone",
  "speaker",
  "headphones",
  "notebook",
  "printer",
  "keyboard",
  "mouse",
  "joystick",
  "gamepad",
  "telescope",
  "microscope",
  "binoculars",
  "compass",
  "map",
  "globe",
  "chef",
  "doctor",
  "nurse",
  "teacher",
  "artist",
  "pilot",
  "firefighter",
  "astronaut",
  "detective",
  "police",
  "judge",
  "lawyer",
  "farmer",
  "builder",
  "mechanic",
  "scientist",
  "programmer",
  "dancer",
  "singer",
  "magician",
  "swimming",
  "skating",
  "skiing",
  "surfing",
  "climbing",
  "juggling",
  "painting",
  "drawing",
  "coding",
  "reading",
  "writing",
  "running",
  "hiking",
  "camping",
  "fishing",
  "gardening",
  "cooking",
  "baking",
  "sewing",
  "knitting",
  "airport",
  "station",
  "library",
  "museum",
  "hospital",
  "school",
  "stadium",
  "theater",
  "market",
  "restaurant",
  "cafe",
  "factory",
  "office",
  "laboratory",
  "workshop",
  "playground",
  "park",
  "zoo",
  "aquarium",
  "gym",
  "helmet",
  "trophy",
  "medal",
  "whistle",
  "anchor",
  "wrench",
  "hammer",
  "screwdriver",
  "ladder",
  "shovel",
  "bucket",
  "magnet",
  "battery",
  "router",
  "satellite",
  "radar",
  "volcano",
  "tornado",
  "igloo",
  "pyramid",
] as const;

const HARD_WORDS = [
  "avalanche",
  "blizzard",
  "drought",
  "eclipse",
  "geyser",
  "tsunami",
  "earthquake",
  "whirlpool",
  "quicksand",
  "meteor",
  "labyrinth",
  "catapult",
  "guillotine",
  "monolith",
  "obelisk",
  "totem",
  "hourglass",
  "crossbow",
  "harpoon",
  "boomerang",
  "chameleon",
  "hedgehog",
  "raccoon",
  "kangaroo",
  "octopus",
  "seahorse",
  "peacock",
  "flamingo",
  "platypus",
  "jellyfish",
  "parachute",
  "zipline",
  "windmill",
  "watermill",
  "lighthouse",
  "drawbridge",
  "skyscraper",
  "greenhouse",
  "observatory",
  "planetarium",
  "origami",
  "mosaic",
  "graffiti",
  "silhouette",
  "portrait",
  "blueprint",
  "sculpture",
  "calligraphy",
  "animation",
  "hologram",
  "algorithm",
  "firewall",
  "blockchain",
  "database",
  "encryption",
  "malware",
  "quantum",
  "nebula",
  "galaxy",
  "asteroid",
  "phoenix",
  "unicorn",
  "griffin",
  "dragon",
  "mermaid",
  "werewolf",
  "vampire",
  "cyclops",
  "minotaur",
  "kraken",
  "samurai",
  "gladiator",
  "pirate",
  "ninja",
  "viking",
  "pharaoh",
  "sultan",
  "monarch",
  "alchemist",
  "oracle",
  "timewarp",
  "afterlife",
  "destiny",
  "gravity",
  "mirage",
  "paradox",
  "entropy",
  "momentum",
  "friction",
  "velocity",
  "camouflage",
  "symmetry",
  "reflection",
  "illusion",
  "gravitywell",
  "brainstorm",
  "moonwalk",
  "tightrope",
  "lockpick",
  "compassrose",
] as const;

const CUSTOM_ALIASES: Record<string, string[]> = {
  apple: ["fruit", "macintosh"],
  banana: ["fruit", "plantain"],
  orange: ["citrus", "tangerine"],
  grape: ["vine", "raisin"],
  pizza: ["pie", "slice"],
  burger: ["hamburger", "sandwich"],
  fries: ["chips", "potatoes"],
  donut: ["doughnut", "pastry"],
  house: ["home", "cottage"],
  car: ["auto", "automobile"],
  bike: ["bicycle", "cycle"],
  plane: ["airplane", "jet"],
  rocket: ["spaceship", "missile"],
  dog: ["puppy", "canine"],
  cat: ["kitten", "feline"],
  rabbit: ["bunny", "hare"],
  turtle: ["tortoise", "terrapin"],
  frog: ["toad", "amphibian"],
  watch: ["timepiece", "clock"],
  glasses: ["spectacles", "eyewear"],
  sofa: ["couch", "settee"],
  phone: ["mobile", "cellphone"],
  laptop: ["computer", "notebook"],
  camera: ["camcorder", "photograph"],
  guitarist: ["musician", "strummer"],
  guitar: ["instrument", "acoustic"],
  violin: ["fiddle", "instrument"],
  piano: ["keyboard", "instrument"],
  drum: ["percussion", "snare"],
  trumpet: ["horn", "brass"],
  microphone: ["mic", "recorder"],
  headphones: ["earphones", "headset"],
  telescope: ["scope", "viewer"],
  microscope: ["scope", "magnifier"],
  binoculars: ["fieldglasses", "viewer"],
  chef: ["cook", "culinarian"],
  doctor: ["physician", "medic"],
  nurse: ["caretaker", "clinician"],
  teacher: ["educator", "tutor"],
  pilot: ["aviator", "captain"],
  firefighter: ["fireman", "rescuer"],
  astronaut: ["spaceman", "cosmonaut"],
  detective: ["investigator", "sleuth"],
  lawyer: ["attorney", "counsel"],
  scientist: ["researcher", "chemist"],
  programmer: ["developer", "coder"],
  dancer: ["performer", "choreographer"],
  singer: ["vocalist", "musician"],
  magician: ["illusionist", "wizard"],
  airport: ["terminal", "runway"],
  hospital: ["clinic", "infirmary"],
  school: ["classroom", "campus"],
  stadium: ["arena", "field"],
  restaurant: ["diner", "bistro"],
  laboratory: ["lab", "research"],
  aquarium: ["fishbowl", "tank"],
  gym: ["fitness", "workout"],
  wrench: ["spanner", "tool"],
  screwdriver: ["driver", "tool"],
  volcano: ["mountain", "eruption"],
  tornado: ["twister", "cyclone"],
  igloo: ["snowhouse", "hut"],
  pyramid: ["triangle", "temple"],
  avalanche: ["snowslide", "landslide"],
  blizzard: ["snowstorm", "storm"],
  tsunami: ["tidalwave", "wave"],
  earthquake: ["quake", "tremor"],
  meteor: ["meteoroid", "fireball"],
  labyrinth: ["maze", "puzzle"],
  catapult: ["trebuchet", "launcher"],
  monolith: ["pillar", "stone"],
  obelisk: ["pillar", "monument"],
  crossbow: ["bow", "weapon"],
  boomerang: ["thrower", "arc"],
  chameleon: ["lizard", "reptile"],
  hedgehog: ["porcupine", "spines"],
  kangaroo: ["marsupial", "jumper"],
  octopus: ["cephalopod", "tentacles"],
  flamingo: ["bird", "wader"],
  platypus: ["mammal", "duckbill"],
  jellyfish: ["medusa", "tentacles"],
  lighthouse: ["beacon", "tower"],
  drawbridge: ["bridge", "castle"],
  skyscraper: ["tower", "building"],
  observatory: ["telescope", "dome"],
  planetarium: ["stars", "dome"],
  blueprint: ["plan", "draft"],
  sculpture: ["statue", "carving"],
  calligraphy: ["lettering", "script"],
  hologram: ["projection", "image"],
  algorithm: ["formula", "logic"],
  firewall: ["security", "barrier"],
  blockchain: ["ledger", "crypto"],
  database: ["storage", "records"],
  encryption: ["cipher", "encoding"],
  malware: ["virus", "spyware"],
  nebula: ["cloud", "space"],
  galaxy: ["milkyway", "cosmos"],
  asteroid: ["rock", "space"],
  phoenix: ["firebird", "rebirth"],
  griffin: ["gryphon", "beast"],
  werewolf: ["wolfman", "lycan"],
  vampire: ["dracula", "undead"],
  cyclops: ["giant", "monster"],
  minotaur: ["bullman", "monster"],
  samurai: ["warrior", "swordsman"],
  gladiator: ["fighter", "arena"],
  pirate: ["corsair", "buccaneer"],
  pharaoh: ["king", "egypt"],
  alchemist: ["chemist", "wizard"],
  timewarp: ["timeslip", "timeloop"],
  gravity: ["pull", "force"],
  mirage: ["illusion", "haze"],
  paradox: ["contradiction", "riddle"],
  entropy: ["chaos", "disorder"],
  momentum: ["inertia", "motion"],
  friction: ["drag", "resistance"],
  velocity: ["speed", "motion"],
  camouflage: ["concealment", "disguise"],
  symmetry: ["balance", "mirror"],
  reflection: ["mirror", "echo"],
  illusion: ["trick", "mirage"],
  tightrope: ["highwire", "balance"],
  lockpick: ["pick", "unlock"],
};

function normalizeWord(value: string): string {
  return value.toLowerCase().replace(/[^a-z]/g, "");
}

function toPlural(word: string): string {
  if (word.endsWith("y") && !/[aeiou]y$/.test(word)) {
    return `${word.slice(0, -1)}ies`;
  }
  if (/(s|x|z|ch|sh)$/.test(word)) {
    return `${word}es`;
  }
  return `${word}s`;
}

function toSingular(word: string): string {
  if (word.endsWith("ies")) {
    return `${word.slice(0, -3)}y`;
  }
  if (word.endsWith("es") && /(ses|xes|zes|ches|shes)$/.test(word)) {
    return word.slice(0, -2);
  }
  if (word.endsWith("s") && !word.endsWith("ss")) {
    return word.slice(0, -1);
  }
  return word;
}

function buildAliases(word: string): string[] {
  const normalizedWord = normalizeWord(word);
  const aliases = new Set<string>();

  for (const alias of CUSTOM_ALIASES[normalizedWord] ?? []) {
    const normalizedAlias = normalizeWord(alias);
    if (normalizedAlias && normalizedAlias !== normalizedWord) {
      aliases.add(normalizedAlias);
    }
  }

  const plural = toPlural(normalizedWord);
  if (plural !== normalizedWord) {
    aliases.add(plural);
  }

  const singular = toSingular(normalizedWord);
  if (singular !== normalizedWord) {
    aliases.add(singular);
  }

  if (aliases.size < 2 && normalizedWord.length > 4) {
    aliases.add(normalizedWord.slice(0, normalizedWord.length - 1));
  }

  return Array.from(aliases).slice(0, 4);
}

function buildPrompt(word: string): CharadesPrompt {
  const normalizedWord = normalizeWord(word);
  return {
    word: normalizedWord,
    aliases: buildAliases(normalizedWord),
  };
}

const EXPECTED_PROMPT_COUNT = 100;

function buildPromptList(words: readonly string[], label: CharadesDifficulty): CharadesPrompt[] {
  if (process.env.NODE_ENV !== "production" && words.length !== EXPECTED_PROMPT_COUNT) {
    throw new Error(`Expected ${EXPECTED_PROMPT_COUNT} ${label} prompts, received ${words.length}.`);
  }
  return words.map((word) => buildPrompt(word));
}

export const CHARADES_PROMPTS: Record<CharadesDifficulty, CharadesPrompt[]> = {
  easy: buildPromptList(EASY_WORDS, "easy"),
  medium: buildPromptList(MEDIUM_WORDS, "medium"),
  hard: buildPromptList(HARD_WORDS, "hard"),
};

export const CHARADES_DIFFICULTIES: CharadesDifficulty[] = ["easy", "medium", "hard"];
